### ISSUE TITLE
Is it possible to get validation messages and do not raise exception?

### ISSUE THREAD

**Issue by greyli** [marshmallow-code/webargs#185]
Hi, guys! I just want use webargs to validate form's data with Flask. What I want is to get the validation error messages and return it to the client ( Then render it in the form ), but the default behavior seems to return a 422 response. So, is it possible to only get validation messages and do not raise exception?

Any help will be appreciated!

**Comment by lafrech** [comment]
The 422 response should contain the validation error messages.

Unless I misunderstand your use case, 422 is the way to go. Let the client get validation error messages from the payload of the 422 response.

**Comment by sloria** [comment]
I agree; the server should return a 422 with the error messages which the client will render.

If you *really* want to, you can subclass `FlaskParser` and override `handle_error` so that it doesn't raise an `HTTPError`.

**Comment by dfee** [comment]
@sloria either you're unaware that people are attempting to use `webargs` to normalize querystring data, or that's a use case you've chosen to not support with this library.

While, I'm no longer rendering to HTML response with Python (going the API / SPA route), `webargs` fails in such a use case as it's expected renderings fail silently rather than throw 422 error messages.

**Comment by sloria** [comment]
> webargs fails in such a use case as it's expected renderings fail silently rather than throw 422 error messages.

I don't think failing silently is the expected behavior. Querystring arguments are validated the same way as other input data. If you don't want an error response to be returned, then the input schema should be made less strict (i.e. fewer validators).

**Comment by dfee** [comment]
To be clear, webargs failing silently isn't marshmallow failing silently. The problem with webargs failing explicitly is that it leaves no control up to the developer of how to handle the exception – short of wrapping your wrapper to catch the thrown exception.

**Comment by lafrech** [comment]
@dfee, IIUC, you're talking about the case where webargs is used to parse query string parameters for a web application that returns HTML to a user via a browser (as opposed to an API talking to a program), and you're saying that you don't want the application to return a 422 to the browser but rather ignore or deal with this in the view function to allow it to return a 200 and a page, maybe with a user-friendly hint about the wrong arguments in the query. Is this correct?

One can subclass `FlaskParser` to override [`handle_error`](https://github.com/sloria/webargs/blob/78d21539095832b15680e575376d4ae12426d65b/webargs/flaskparser.py#L99) and implement a new `handle_error` without the abort. However, the view function will receive nothing. Neither the error messages nor the partial result (parameters that were parsed correctly).

I didn't try anything, but I think this could be addressed with a slight modification of [`Parser.parse`](https://github.com/sloria/webargs/blob/4533a5594b7bc9983f28b62c2d06d05205c6cdf1/webargs/core.py#L369). In the `except` case, we could put the partial result in `ret` so that successfully deserialized parameters are injected in the view rather than `None` if `handle_error` does not abort. This shouldn't break current behaviour. Regarding the error messages, well, maybe the `handle_error` override could store them in the request context but this doesn't look so nice. And it is Flask-specific. But I don't see any non-breaking way to inject this in the view function. And the more I think of it, the more I think that, like @sloria says, the right way is to do little validation: use `String` fields and do the deserialization in the view function.

**Comment by dfee** [comment]
@lafrech that's right – as I'm not using Flask, I'm sure there is an alternative to `FlaskParser`, but your point stands. Ultimately, I needed to move on from `webargs` as I needed to do two things:
1) validation for a view (partial validation is worse than no validation due to the mental overhead of now dealing with two validators)
2) modification of the payload (what marshmallow returns as `data`) and re-serialization; i.e. building custom querystrings based on toggling.

I'm actually just back to using graphql + a js framework instead of handling HTML rendering and querystring validation in Python. For object validation, that is now a task for Marshmallow directly, if I so choose.

**Comment by n0nSmoker** [comment]
Flask parser works strange it calls abort function and flask returns html page without messages, you can check it yourself. So the @greyli  is absolutely right.
For those who also suffer from that strange behaviour here's my solution:
```python
from flask import abort
from webargs.flaskparser import FlaskParser
from flask import jsonify, make_response

def fail(msg, status=400):
    """
    Generates JSON error msg
    :param msg: Error message(s)
    :param status: Status code
    :return:
    """
    if not isinstance(msg, list):
        msg = [msg]
    return make_response(jsonify(dict(errors=msg)), status)

class Parser(FlaskParser):
    def handle_error(self, error, req, schema,
                     error_status_code, error_headers):
        response = fail(
            [f"Field:{k}. {' '.join(v)}" for k, v in error.messages.items()]
        )
        abort(response)

parser = Parser()
```
So use this parser instead of the default one.
I also disagree that you should return 422 code instead 400 these are different codes for different situations.
