### ISSUE TITLE
test_error_handler_is_called_when_regardless_of_schema_strict_setting looks fishy

### ISSUE THREAD

**Issue by lafrech** [marshmallow-code/webargs#187]
I might be missing something, but I think there's something wrong in this test:

[test_error_handler_is_called_when_regardless_of_schema_strict_setting](https://github.com/sloria/webargs/blob/dev/tests/test_core.py#L719).

`viewfunc2` is created but unused and `viewfunc` is called twice with the same parameters.

The test title (I guess it should read `test_error_handler_is_called_regardless_of_schema_strict_setting`) suggests that the code should be 

```python
        with pytest.raises(CustomError) as excinfo:
            viewfunc()
        assert excinfo.value.args[0] == {'email': ['Not a valid email address.']}

        with pytest.raises(CustomError) as excinfo:
            viewfunc2()  # <-- viewfunc2 here
        assert excinfo.value.args[0] == {'email': ['Not a valid email address.']}
```

except `viewfunc2` does not raise because the schema is not strict.

I'm not sure what the intent was in this test.

**Comment by sloria** [comment]
Ah, good catch. That test turns out to be junk. (1) It doesn't test what it's intending to test and (2) it's not testing the desired API.

You are correct about the typo--it should be calling `viewfunc2()`. However, if `strict` isn't `True`, we don't expect the error handler function to be called. That's why we have this warning:

https://github.com/sloria/webargs/blob/4fe17a4434c0bc6f47ccccf8a7245df59549eedf/webargs/core.py#L291-L293 .

I've removed the test on `dev`.
