### ISSUE TITLE
Customize argument dictionary

### ISSUE THREAD

**Issue by vasudevanv** [marshmallow-code/webargs#441]
I have a use case where some keys in the request JSON depend on others. An example is

```json
{
  "item_type_list": ["a", "c", "a", "b"],
  "items" : [ 
    { 
      "value": 1
    }, 
    { 
      "center": 2, 
      "value": 2 
    }, 
    { 
      "value": 3 
    },
    {
      "border": 5, 
      "value": 2, 
      "btype": "solid"
    } 
  ]
} 
```
The value of `item_type_list` determines the type of each dict entry in `items`. Is there a method I could use to construct a custom argument dictionary for `use_args`? 

Using marshmallow schema factories seems a little cumbersome. Having a way to customize the argument dictionary might be useful. For example I am thinking of a construction similar to the the marshmallow schema factory

```python
def make_custom_argdict(request):
    example_custom_arg_dict = { }
    # do something with request.json
    # .......
    return example_custom_arg_dict

class MyCustomResource(Resource):
    @use_args(make_custom_schema)
    def post(self,args):
        # do stuff with request 
        return result
```

**Comment by lafrech** [comment]
Is the list of types known at schema creation time? From your example, it looks like the types are defined in the input payload.

Assuming you're doing things at schema creation time, I don't know how to deserialize elements from a list with different schemas based on the index in the list, so it sounds like you need some factory indeed to overload the `List` field. 

If you need this done dynamically based on the input, you could be interested in the issues tagged [polymorphism](https://github.com/marshmallow-code/marshmallow/issues?utf8=%E2%9C%93&q=label%3Apolymorphism+) in marshmallow bugtracker, although your case is a bit different because the type is defined in somewhere in the payload, not at item level.

**Comment by vasudevanv** [comment]
Thanks a lot for the quick response. Indeed, the types are defined in the input payload. I would like it to be done dynamically based on the input. I will take a look at the polymorphism issues in the marshmallow bugtracker and see if I can get any ideas. 

Is there a plan to support some sort of factory for overloading fields in the future?

**Comment by vasudevanv** [comment]
Thank you very much @lafrech, after some minor adjustments to my inputs, I was able to get marshmallow-oneofschema to work for my case. Closing this issue.  

Here is the sample code for reference.

```python
# Nested marshmallow schema    
class TypeASchema(marshmallow.Schema):
    a = marshmallow.fields.Number()
    b = marshmallow.fields.Number()

class TypeBSchema(marshmallow.Schema):
    r = marshmallow.fields.Number()

class PolymorphicSchema(OneOfSchema):
    type_schemas = {"typea": TypeASchema, "typeb": TypeBSchema}

class MasterSchema(marshmallow.Schema):
    items = marshmallow.fields.Nested(PolymorphicSchema, many=True)

class MyResource(Resource):
    """Nested marshmallow API

    Notes
    -----
    This parses a request of the form
    {
	"name": "test",
	"items": [
	    {
                "type": "typea",
                "a": 1,
	        "b": 1.0
            },
            {
                "type" : "typeb",
                "r": 2.0
            }
	]
    }
    """
    @use_kwargs({"name": webargs.fields.Str(required=True)})
    @use_args(MasterSchema)
    def post(self, args, name):
        print(args)
        return {'name': name, 'items': args['items']}
```
