### ISSUE TITLE
django: webargs raise 500 on validation errors as opposed to 400

### ISSUE THREAD

**Issue by nicholasamorim** [marshmallow-code/webargs#528]
I'm not sure if this is intentional. I know that the view is responsible for handling `ValidationError` but the thing is.. if I use marshmallow directly:

```python
from rest_framework.views import APIView

class TestHandler(APIView):
	def post(self, request, *args, **kwargs):
		serializer = SearchRequestSchema(data=self.request.data)
	    serializer.is_valid(raise_exception=True)
```

Any problem in validation will properly raise a 400 with proper response.

But if I do this:

```python
from rest_framework.views import APIView

class TestHandler(APIView):
	@use_args(SearchRequestSchema(), location="json")
	def post(self, request, data, *args, **kwargs):
	    pass
```

A 500 is raised.

```
    error_headers=error_headers,
  File "/Users/nicholas/.virtualenvs/sm2accounts/lib/python3.7/site-packages/webargs/core.py", line 537, in handle_error
    raise error
  File "/Users/nicholas/.virtualenvs/sm2accounts/lib/python3.7/site-packages/webargs/core.py", line 260, in parse
    result = schema.load(location_data)
  File "/Users/nicholas/.virtualenvs/sm2accounts/lib/python3.7/site-packages/marshmallow/schema.py", line 723, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/Users/nicholas/.virtualenvs/sm2accounts/lib/python3.7/site-packages/marshmallow/schema.py", line 904, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'instance_id': ['Invalid value.']}
```

I'm not exactly sure why they behave differently if supposedly the same kind of exception is raised.

**Comment by sirosen** [comment]
This doesn't look to me like a marshmallow or webargs issue.

We can't tell from the above what type of object `SearchRequestSchema(data=...)` is returning, but something is happening here which is user-code -- we know right away because that `is_valid` method is not provided by webargs or marshmallow. It has to be coming from somewhere else.

webargs calls `schema.load(...)` with a user-provided schema object (and it instantiates schema classes for you), but it won't invoke your `is_valid` method. So the two examples you gave are not comparable.
The comparable code for your webargs usage would be
```python
from rest_framework.views import APIView

class TestHandler(APIView):
    def post(self, request, *args, **kwargs):
        data = SearchRequestSchema().load(self.request.data)
```

Does this help to explain the problem?

Webargs decorators can raise ValidationErrors. Your application needs to be prepared to handle those and potentially re-throw them as framework-specific errors.
You could set the `error_handler` for the django parser as a way of doing this:
https://webargs.readthedocs.io/en/latest/quickstart.html#error-handling

**Comment by sirosen** [comment]
I'm closing this, since there's been no further activity. I hope my prior answer was sufficient for you to figure out what's happening. If not, please just say so.
