### ISSUE TITLE
Upgrading from v5.5: 6.1.1 or directly to 7.0b1

### ISSUE THREAD

**Issue by ThiefMaster** [marshmallow-code/webargs#561]
Now that my [project](https://github.com/indico/indico) finally uses Python 3 and I already upgraded marshmallow and everything else, webargs is the last missing dependency upgrade.

v5 to v6 already requires many changes to all the `@use_kwargs` where the location isn't the JSON payload (which is exactly what I waited to the very end with this one ;)), but v6 to v7 looks pretty easy.

So I wonder if I should just upgrade to v6 or go straight for v7 - especially taking into account that the version of my project where I'll upgrade from v5 won't be released for another 1-2 months (but of course I don't know how fast you plan to get from b1 to a rc or final release)

**Comment by lafrech** [comment]
Regardless of v7 release date, I don't think it is easier to go straight to v7 than to do it in two steps. In fact, even if v7 was released already, I'd probably do it in two steps, moving to v6 first, to minimize the changes. This is a general rule of thumb. Unless a change in v7 sort of cancelled a change in v6 (I can't think of any in this case), moving to v6 first has no extra cost.

**Comment by sirosen** [comment]
I think going straight to v7 _might_ be easier if you have cases where you're using a dict-schema like
```
@use_kwargs({"param1": fields.Int()}, location="query")
def foo(param1):
    ...
```

Under v6, schemas are constructed with the default for marshmallow for the `unknown` parameter, `unknown=marshmallow.RAISE`. As a result, the above example will reject unknown query parameters.
In v5, webargs would pick fields out of the request in a way pretty much the same as `unknown=marshmallow.EXCLUDE`.

A few people found this problematic after v6 was released. You could always workaround it by creating a Schema and setting `unknown` yourself, but I think it makes dict-schemas hard to use in v6.

Probably the biggest feature being added in v7 is the fix for this: flexibility to control the `unknown` value.

If you're never or rarely using dict-schemas, I agree with @lafrech that you probably don't gain from jumping straight to v7.
If that's the case, I'd say you should go to v6 first, since we're still finalizing v7. Moving from v6 to v7 should be super-duper easy because not very much is changing other than the features around `unknown`.

**Comment by ThiefMaster** [comment]
Thanks, that's really helpful - I do indeed use dict-based schemas quite a lot, so I'll have a quick look how much breaks with v6 and then try v7.
