### ISSUE TITLE
`is_multiple` vs custom fields

### ISSUE THREAD

**Issue by ThiefMaster** [marshmallow-code/webargs#563]
Right now I don't get multiple values in a custom field that does not inherit from the `List` field because `is_multiple` only checks for this.

And for some cases rewriting the field to be nested in an actual List field is not feasible, for example a `SQLAlchemyModelList`-like field where sending individual queries would be inefficient compared to one query with an SQL `IN` filter.

I propose adding a `MultiValueField` which would simply inherit from Field and do nothing itself, and instead of checking for isinstance List check for that one in `is_multiple`. `List` would then of course inherit from that instead of `Field`.

Alternatively, check for something like `isinstance(field, List) or getattr(field, 'is_multiple', False)`.

I can send a PR if there's interest in this.

**Comment by sirosen** [comment]
I admit that I might not be well enough educated about marshmallow-sqlalchemy (I've never used it) to be able to make a good judgement about that part of this issue. But clearly, `is_multiple` isn't very extensible right now, and that's a problem. (Also, I think it doesn't handle `Tuple`? So that's a bug.)

If we put `MultiValueField` into `marshmallow`, that might get confusing with `Nested(..., many=True)` as a possibility. I think `is_multiple` makes more sense as a characteristic of a field instance than a field class -- that makes it possible (at least in theory) to have a field whose instances vary with respect to this.

As a result, I think the `getattr` solution is the right one. `is_multiple` seems like a reasonable name for the attribute to me. @lafrech, do you maybe have a different opinion about this, or any thoughts about naming?

**Comment by sirosen** [comment]
Although this was closed in #584, I'm working on a follow-up change that should document the interface for this and make it even easier to customize. I plan to put that together potentially for v7.1.0 .
I'll try to remember to follow up here when we release the new version, but I may forget.

**Comment by sirosen** [comment]
I just pushed out v8.0 , which turned out to be the first version supporting `is_multiple` on fields.

In contrast with the last couple of major releases in webargs, this one has fairly modest changes, so it should be fairly easy to update.

**Comment by lafrech** [comment]
Great. Thanks.

**Comment by lafrech** [comment]
I did a few CHANGELOG updates. I don't think it was worth a PR so I pushed to dev.

**Comment by lafrech** [comment]
Also we might want to add a paragraph in the upgrading section of the docs.

https://webargs.readthedocs.io/en/latest/upgrading.html
