### ISSUE TITLE
Add "bundle_errors" options to send multiple errors for one parse

### ISSUE THREAD

**Issue by jfpoilpret** [marshmallow-code/webargs#58]
Hi, I just started using **webargs** with the purpose to fully replace `reqparse` from **Flask-RESTful** in my application.
So far I am very happy with webargs nested arguments capabilities (which I could not properly work out with reqparse).

However, with reqparse you have a `bundle_errors` option, which when set to `true`, tries to validate all arguments and does not stop after the first error, but rather aggregates all errors and throws an exception which `message` field is a dictionary with all errors found per field.

This option is very useful to avoid many roundtrips between client and server when you have a complex form or web service.

I could not find an equivalent feature in webargs, does such a feature exist? If not, it would be very nice to have and that would put webargs to par (and even better) with reqparse.

**Comment by sloria** [comment]
"Error bundling" has not yet been implemented in webargs, though it's definitely a feature I would like to see.

One solution is to use [marshmallow](https://github.com/marshmallow-code/marshmallow) in tandem with webargs (I see Flask-RESTful is working towards replacing it's marshalling module in favor of marshmallow) because it does have the error-bundling you're looking for. You would use `webargs` solely to pull arguments off of the request, then leave validation up to marshmallow. There is even some work being done to provide tighter integration between the two libraries: https://github.com/hartror/webargs-marshmallow .

I would accept a PR implementing this feature in webargs, but for the time being, marshmallow's validation is the way to go.

**Comment by jfpoilpret** [comment]
Thanks for the comment.
Currently I don't use marshmallow in my project as the marshalling support of Flask-RestFul fits my needs for output; I am not sure yet I would want to add it as a new dependency just for this.

I will take a look at webargs source and see if I can easily add this feature and propose a PR for it. However, I think that won't be until a few weeks more.

I will put updates here if needed.

**Comment by marcellarius** [comment]
A related change that I had considered making was to catch ValidationError exceptions during parsing and ensure the arg name was set -- as validation functions probably won't know the correct arg name when raising the exception.

**Comment by sloria** [comment]
This is solved by using marshmallow for validation.
