### ISSUE TITLE
Allow `use_args` to accept `marshmallow.Field`

### ISSUE THREAD

**Issue by joshfriend** [marshmallow-code/webargs#606]
I would like to parse a simple list of values, for example:

```json
["a", "b", "c"]
```

This code does not work because `use_args` requires a `Schema` object or a `dict` which approximates one, but this is what I would have though could be an intuitive way to parse the above json:

```python
@app.route('/')
@use_args(fields.String, many=True)
def example(args: List[str]):
    pass
```

Since this does not work, I can only seem to deserialize objects, or lists of objects:

```json
[
  {"value": "a"},
  {"value": "b"},
  {"value": "c"}
]
```

```python
class ValueSchema(Schema):
    value = fields.String()

@app.route('/')
@use_args(ValueSchema(many=True))
def example(args: List[ValueSchema]):
    pass
```

Can flat lists of "plain" values be supported somehow?

**Comment by sirosen** [comment]
I don't think such a feature is a good idea. It would be a lot of work for `webargs` in order to support a very particular and limited usage.

One of the issues is that it only makes sense for the `json` location. For other locations like `headers` or `query`, data is always going to be a mapping, not a list.

Since `webargs` is all about using `marshmallow` to parse API inputs, it's worth asking how you would load data in the shape `["a", "b", "c"]` with `marshmallow`.

I think the easiest way is a schema with `pre_load` and `post_load` hooks which puts the whole body into a field. For example:
```python
class MySchema(Schema):
    data = fields.List(fields.String())

    @pre_load
    def wrap(self, data, *args, **kwargs):
        return {"data": data}

    @post_load
    def unwrap(self, data, *args, **kwargs):
        return data["data"]
```

That said, if you're designing a new API (vs handling a legacy one), I'd recommend considering putting the data in an object envelope, like `{"content": ["a", "b", "c"]}`. That way, you can easily add new fields in the future.
Lots of people have different opinions about APIs that consume or produce JSON arrays, so not everyone would agree with that guidance. But that's my $0.02 on the topic.
