### ISSUE TITLE
Nested Fields Usage

### ISSUE THREAD

**Issue by imhoffd** [marshmallow-code/webargs#74]
I've looked through the documentation and source code and now I just have to ask.

How do I format requests for endpoints that utilize nested fields? Can more documentation be written about nested fields than [what exists currently](http://webargs.readthedocs.org/en/latest/quickstart.html#nesting-fields)?

**Comment by sloria** [comment]
Nested fields are useful for validating JSON bodies in requests.

What documentation do you think should be added? I would welcome a PR adding docs.

**Comment by imhoffd** [comment]
That's the part I didn't understand: that they can only be used with the **json** location.

As a side note, nesting of fields in query params and form params _could_ be possible with a delimiter, such as when querying in MongoDB.

`/people?name.first=Daniel&name.last=Imhoff` for example.

Would this interest you? Or do you think that is assuming too much, as it does reserve a character in webarg names that would otherwise be acceptable.

**Comment by sloria** [comment]
Indeed, `Nested` fields only make sense for JSON bodies with the default implementations because that's the only place you'll find nested data on the request.

You could, however, implement a parser that could read nested query parameters, though I do not think this functionality belongs in webargs. I know that filteralchemy (which uses webargs internally) has the concept of custom formatters for query params: https://filteralchemy.readthedocs.org/en/latest/quickstart.html#customizing-query-format .

**Comment by imhoffd** [comment]
:+1:
