### ISSUE TITLE
[Question] how to use this with line item like data?

### ISSUE THREAD

**Issue by simkimsia** [marshmallow-code/webargs#743]
let say i have a product_package and product_package_line_items how do I prepare the data?

```json
{'name': 'Cleanup w/ feeder cable re-grooming', 'product_package_line_items.3.id': '1750', 'product_package_line_items.0.id': '1747', 'product_package_line_items.4.quantity': '1.00', 'product_package_line_items.4.id': '1751', 'product_package_line_items.3.quantity': '1.00', 'product_package_line_items.1.product_id': '15079', 'product_package_line_items.2.id': '1749', 'product_package_line_items.0.product_id': '15075', 'product_package_line_items.3.product_id': '15029', 'product_package_line_items.5.id': '1752', 'product_package_line_items.5.product_id': '17317', 'product_package_line_items.1.quantity': '6.00', 'product_package_line_items.2.product_id': '15088', 'product_package_line_items.2.quantity': '1.00', 'product_package_line_items.5.quantity': '1.00', 'product_package_line_items.4.product_id': '15134', 'product_package_line_items.1.id': '1748', 'product_package_line_items.0.quantity': '2.00', 'save_and_edit': ''}
```

```python
class DraftProductPackageLineItemSchema(Schema):
    """
    schema to create DraftProductPackageSchema
    """
    id = fields.Int(required=False)
    product_id = fields.Int(required=True)
    quantity = fields.Decimal(places=2, required=True)

class SaveProductPackageSchema(Schema):
    """
    schema to save SaveProductPackageSchema
    """
    name = fields.Str(required=True)
    product_package_line_items = fields.List(fields.Nested(DraftProductPackageLineItemSchema))



# https://webargs.readthedocs.io/en/latest/framework_support.html#django
@parser.use_args(DraftProductPackageSchema(unknown=EXCLUDE), location="form")
@require_http_methods(["POST"])
def product_package_create_post(request, request_args):

```

I was expecting the request_args to be like

```python
request_args["name"] # <== this exists
request_args["product_package_line_items"] # <== this doesn't show up as a list of dictionary with id, product_id, quantity 
```

how should i change things?

**Comment by sirosen** [comment]
It looks to me like your schema is expecting a list, but your data is not a list. From the marshmallow/webargs perspective, this is kind of cut-and-dried -- if you want to validate and parse list data, you need to start out with list data.

It's hard for me to say how you should or should not design your application -- everyone has to make their own choices, `webargs` is here to help make that possible! -- however, I would not recommend trying to pack any list-like data into a form POST. Form-encoded data is always going to be an awkward fit for arrays.

I would suggest trying to use JSON data if you're building a web application which consumes lists. JSON has an array type, which will make this much easier.

If you _must_ use a FORM post, and you _must_ pass an array of items, we enter the territory of "it's software, so anything is possible". You can pre-process your data before it reaches webargs at all, or before webargs passes it to your schema using [`pre_load`](https://webargs.readthedocs.io/en/latest/advanced.html#parser-pre-load).

---

The Mozilla docs on web dev are really fantastic, and I strongly recommend reading [this doc on POST](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST) in order to better understand the limitations of form data. In particular, consider the implications of this snippet of doc:
> the keys and values are encoded in key-value tuples separated by '&', with a '=' between the key and the value. Non-alphanumeric characters in both keys and values are [percent encoded](https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding): this is the reason why this type is not suitable to use with binary data (use multipart/form-data instead)

That sounds a lot like query-param encoding because it is exactly the same as query-param encoding! So think to yourself "if I can't express it in query params, I probably can't express it in form data", and you'll be alright.

(For more fun reading, the spec which defines the form-urlencoded format: https://url.spec.whatwg.org/#application/x-www-form-urlencoded )

---

There are strong elements of this which aren't really a webargs questions, but general web development questions which _happen_ to use webargs. As such, there is not going to be any clear point at which this is "closed". We could probably be pedantic and mark this as `invalid` or something and close it, but that's not very nice.

I'd rather use SO for such questions (because then I don't need to break my head over what it means to close a question...), but if they show up in this tracker, it's fine. I check SO for webargs questions pretty irregularly anyway.

All that said, this answer is as complete as I can make time for right now, and it should put you on the right track. So I'm going to close now.

**Comment by simkimsia** [comment]
> That sounds a lot like query-param encoding because it is exactly the same as query-param encoding! So think to yourself "if I can't express it in query params, I probably can't express it in form data", and you'll be alright.

Oh this is great. Thank you @sirosen 

And yes, i agree that there are strong elements of this that are to do with general web dev. I appreciate you not being pedantic and simply marking it as invalid.

And I also agree if i have follow up questions, I should post in SO.

All in all, thank you. Your handling of this question is impressive and thoughtful. Thank you 🙇🏻‍♂️

## Postscript

I kept the schema I wrote in the original question as is and in the html markup side of things i have also kept as form data but I used hidden fields this way

![image](https://user-images.githubusercontent.com/245021/179472271-a3187afd-7b77-4d69-aee7-3cf9a5412f49.png)

```html
<input type="hidden" name="product_package_line_items.0.id" value="1747">
<input type="hidden" name="product_package_line_items.0.product_id" value="15075">
<input type="hidden" name="product_package_line_items.0.quantity" value="2.00">
<input type="hidden" name="product_package_line_items.0.id" value="1748">
<input type="hidden" name="product_package_line_items.0.product_id" value="15079">
<input type="hidden" name="product_package_line_items.0.quantity" value="6.00">
```
