### ISSUE TITLE
Being able to handle ValidationError in Flask view methods without custom error handler

### ISSUE THREAD

**Issue by gh-andre** [marshmallow-code/webargs#824]
webargs 8.2.0, Flask 2.2.3, Python 3.10

It would be helpful if it was possible to just catch `ValidationError` in a view method, without having to implement a dummy custom error handler. Here's a quick example.
```Python
import flask
import webargs
from webargs.flaskparser import parser as flask_parser

abc_args = {
    "name": webargs.fields.Str(required=True, validate=webargs.validate.Length(min=6)),
    "email": webargs.fields.Email(required=True)
}

app = flask.Flask("myapp")

def abc() -> flask.Response:
    try:
        args = flask_parser.parse(abc_args, flask.request, location="query")
    except webargs.ValidationError as error:
        return flask.Response(f"Bad args: {error.messages}")

@flask_parser.error_handler
def handle_error(error, req, schema, *, error_status_code, error_headers):
    # error is ValidationError in this case
    raise error

app.add_url_rule("/abc", view_func=abc)
app.run()
```
Request this URL to see the result.

localhost:5000/abc?email=abc&name=xyz

Without the error handler, it will return status code `422`, which works for REST API type of apps, but for apps serving HTML pages errors often need to be rendered as successful status codes, with error messages shown to the user, so they can take corrective action. 

Having this custom handler seems to be the only way to return the response above. Moreover, this handler can only be set via a decorator, which doesn't work at all if `Flask` is allocated within some custom class and not as a global. Flask allows this use by providing methods like `Flask.add_url_rule`, which can be called without using decorators.

It would be nice if it was possible to catch `ValidationError` in a view method without a custom error handler. It would be even nicer if there was a method in `FlaskParser` that would allow setting the error handler without a decorator.

**Comment by sirosen** [comment]
I believe that it is already possible today to do what you're asking for, but I may be misunderstanding what you're looking to do.

You mention APIs vs webapps, but I think the distinction is not necessary. webargs aims to put the tools to satisfy both of these use-cases into the hands of its users. I think this confuses the behavior of the default flask error handler (simple, unfussy, but also unsophisticated) with the behaviors which are possible and the tools which are provided.

There is, as you've noted, a decorator-based interface for attaching error handlers, but I'll note that decorators are just syntactic sugar and don't need to be called in module scope. The `error_handler` decorator registers the decorated function with the parser and returns the decorated function unmodified, so it's safe to simply call it whenever you want to set the error handling function.

```python
def handle_error(error, req, schema, *, error_status_code, error_headers):
    raise MyCustomError(error.messages)

myparser = FlaskParser()

def create_app() -> Flask:
    app = Flask(__name__)
    myparser.error_handler(handle_error)
    return app
```

There's also the fact that you can subclass `FlaskParser` to customize the behavior more thoroughly. e.g.
```python
import typing
from marshmallow import Schema, ValidationError
from webargs.flaskparser import FlaskParser

class CustomFlaskParser(FlaskParser):
    def handle_error(
        self,
        error: ValidationError,
        req: typing.Any,
        schema: Schema,
        *,
        error_status_code: int,
        error_headers: typing.Mapping[str, str],
    ) -> typing.NoReturn:
        raise CustomValidationError(
            "Request failed input validation.", error_data={"messages": error.messages}
        )
```

So I'm not seeing any new features or improvements that are needed for this use-case; only clarification about the existing ones. (And I'm always very much open to new or enhanced docs.)

To your second-to-last note:
> It would be nice if it was possible to catch `ValidationError` in a view method without a custom error handler.

You can either define a custom parser subclass which does what you want, alter the error handler, or catch the flask abort which is used by the out-of-the-box default. I think this is already a broad enough suite of options for ways of doing this, so I'd be extremely hesitant to add another path.
I'm also not hearing a clear proposal here for what the new interface would or should be, which makes it hard to discuss further.

To your final note,

> It would be even nicer if there was a method in `FlaskParser` that would allow setting the error handler without a decorator.

This is already possible. I would be happy to review a PR for a doc change to clarify this with an example, but I'm not sure it's necessary.

This only matters in a pretty narrow case, in which you are intentionally coupling the declaration of your webargs parser with the creation and instantiation of objects which will be used by your application. I would tend look at that as an unnecessary tight coupling between parsing and the rest of an application, but I'm sure there are sophisticated use-cases in which it makes sense.

**Comment by gh-andre** [comment]
@sirosen Thank you for a detailed response.

> You mention APIs vs webapps, but I think the distinction is not necessary.

There's one, actually, in that on a web page one won't return an HTTP error, but rather `200` and render error messages for users to fix validation issues. In a REST API none of that is necessary and one can always return an error HTTP status and a response body with validation fields. Current behavior works well for the latter, but requires additional handling and custom error handler for something as simple as being able to catch a `ValidationError`.

More complex cases can require both. Consider a referring URL being added for a login request. On a page like this, a malformed referring URL would be nefarious and would require an HTTP error, but bad user name and password would require a successful response and validation messages.

> but I'll note that decorators are just syntactic sugar

Not quite. Decorators run before any instances are created, which forces one to use global functions. So, it's not the module scope that matters as much as that one is limited in what functions can be registered via decorators, since there's no instance available at the time a decorator runs. For own code it can be worked out with partials and explicit `self`, but when 3rd-party calls it, there isn't much choice but to use a global function.

Flask does provide decorators, but also allows one to set up view handlers as methods via `Flask.add_url_rule`, which works out well for class-based apps.

> so it's safe to simply call it whenever you want to set the error handling function.

It's actually simpler - in order to accomplish what I'm describing I don't need to translate `ValidationError` to a custom error, but it just requires something like this.

```
def handle_error(error, req, schema, *, error_status_code, error_headers):
    raise error
```
, which achieves the behavior I'm describing with this dummy error handler.

I will also note that there's a discrepancy in behavior (as far as I can tell, unless I'm missing something) between how `core.Parser` handles the error and `FlaskParser` does in that the latter calls `Flask.abort`, which raises a completely different exception, while the former simply rethrows `ValidationError`. 

> This is already possible. I would be happy to review a PR for a doc change to clarify this with an example

I must've missed this. I will review the code tomorrow.

> you are intentionally coupling the declaration of your webargs parser with the creation and instantiation of objects

Not sure what you mean. The whole issue is about being able to avoid using global functions and behavior defined by global functions. All I was looking for was to catch a validation error in a method where it happened. Don't see any coupling here, really.

> You can either define a custom parser subclass which does what you want, alter the error handler

Yes, I did work it around and posted here thinking that it would be useful to simplify this workflow by just catching a validation error in the method where it was triggered, which seemed straightforward to me. Having said that, I fully understand if it does not agree with the philosophy of this framework. Please feel free to close this issue.

Thanks again for the response and also for the framework. Not a lot of schema-based validation packages out there :)

**Comment by sirosen** [comment]
> There's one, actually, in that on a web page one won't return an HTTP error, but rather `200` and render error messages for users to fix validation issues. In a REST API none of that is necessary and one can always return an error HTTP status and a response body with validation fields. Current behavior works well for the latter, but requires additional handling and custom error handler for something as simple as being able to catch a `ValidationError`.
> 
> More complex cases can require both. Consider a referring URL being added for a login request. On a page like this, a malformed referring URL would be nefarious and would require an HTTP error, but bad user name and password would require a successful response and validation messages.

You are talking about how you would like error handling in your web application to work. Not about how browsers work or what HTTP, HTML, or any other protocol specifies. Browsers are perfectly happy to render HTML for non-200 statuses, for example.

These different usages all look the same to `webargs`'s core and to most of the parsers. It parses some input using `marshmallow`, wraps any error to show which location failed, and invokes your configured error handler. Nothing in that process is predisposed towards one type of web-facing application or another -- the supposition is that `webargs`'s job is primarily to throw errors and catch them with configured error handlers.

For the most part, translation of errors into responses is a domain that the library does not even try to address. Arguably, providing any default error handlers -- like the one for `flask` -- biases the library in one direction, but I don't think this is such a bad thing. After all, these are only defaults, and the design is meant to put the tools to do whatever you want at your disposal, including replacing those defaults with behaviors that better match your use-case.

The alternative would be to provide no defaults, which not only provides less value for users who like the current default, but also makes it harder for users to learn how to write these handlers themselves, as there are fewer good (and tested) examples.

> > but I'll note that decorators are just syntactic sugar
> 
> Not quite. Decorators run before any instances are created, which forces one to use global functions.

No, that's what happens _if_ you use a decorator in module scope.

A decorator `foo` used on a function bar like so:
```python
@foo
def bar(): ...
```
is syntactic sugar for
```python
def bar(): ...

bar = foo(bar)
```

That's what the decorator syntax means. It's a nice syntax for a function which takes a function as its argument (and typically returns a function as its result, but it could be some other object, e.g. like how `click.command` returns a `Command` object).

If you look at the source for `error_handler` in `webargs`, you'll see that, sans annotation and docs, it looks like this:
```python
def error_handler(self, func):
    self.error_callback = func
    return func
```

Which means that there is no difference between the following two snippets:
```python
# decorator syntax
@parser.error_handler
def foo(...): ...

# explicit function call syntax
def foo(...): ...

parser.error_handler(foo)
```

Given that `error_handler` returns the original function unmodified, that should lead us to conclude that one could construct a parser and set its `error_callback` by calling `error_handler` at any time.

Like I said, I'm more than happy to take a doc suggestion if you think there's a place where such usage could be clarified.

> I will also note that there's a discrepancy in behavior (as far as I can tell, unless I'm missing something) between how `core.Parser` handles the error and `FlaskParser` does in that the latter calls `Flask.abort`, which raises a completely different exception, while the former simply rethrows `ValidationError`.

Yes, there is a difference. `FlaskParser` has a default error handler which is Flask-specific. The base class can't make any assumptions about the framework being used and therefore it can't do anything very interesting, so it does basically nothing and rethrows the exception it's been given.

This seems to be at the core of the issue that you're trying to describe. It sounds like you would have preferred that the flask parser not set a default handler, and just used the one provided by the base parser.

Other users are likely relying on the default error handler for the flask parser, so removing or changing it would break their existing usages. So if you would like us to remove the customizations from `FlaskParser` which call `flask.abort()`, that's basically a non-starter.

I still think this is a use-case which can be best addressed through documentation, since I don't see any clear changes which would've made this easier for you.

> > you are intentionally coupling the declaration of your webargs parser with the creation and instantiation of objects
> 
> Not sure what you mean. The whole issue is about being able to avoid using global functions and behavior defined by global functions. All I was looking for was to catch a validation error in a method where it happened. Don't see any coupling here, really.

The sign of tight coupling is that you _care_ that the error handler is typically defined as a simple function. (And as I'm trying to make sure is clear, it doesn't have to be.) That indicates that you are trying to hook your error handler into some broader framework in a way that I would _typically_ recommend against.

Everyone's use-case is different, so I'm in no position to advise you or criticize your usage. But I think the reason you see a mismatch between what the documented examples for `webargs` show and what you are doing is that for most users such a design is a bad idea.

> Yes, I did work it around and posted here thinking that it would be useful to simplify this workflow by just catching a validation error in the method where it was triggered, which seemed straightforward to me.

I wouldn't characterize that as a workaround? It seems to me more like using the framework as designed.

I didn't understand at first that you were saying that you have code like your example above and you are looking to simplify it.

You said:

> Moreover, this handler can only be set via a decorator, which doesn't work at all if `Flask` is allocated within some custom class and not as a global.

Which is what I've been focused on. In two points:

1. The decorator interface can be simply called if your use-case demands it
2. You should probably have some separation of responsibilities such that parsing throws a well-defined error type for your application, and your application (e.g. via _its_ top-level error handlers) is responsible for rendering that error to a user-facing response

(1) addresses something which I think you've been unclear about with respect to how decorators behave and how the `error_handler` one can be used.

(2) is a matter of application design, but I recommend considering it. Such a design which isolates parsing from the rest of your application will tend to be more testable.

Going back to your original message,

> It would be nice if it was possible to catch `ValidationError` in a view method without a custom error handler. It would be even nicer if there was a method in `FlaskParser` that would allow setting the error handler without a decorator.

I now better understand what you were asking for.

You asked for this support "without a custom error handler". I don't see an interface for this which is _superior_ to setting an error handler -- although I can come up with plenty of alternatives which become confusing to maintain and explain.

To the second part, allowing you to set the error handler without using the decorator syntax, that is already possible today. I think that's the most important thing I want to make sure is clear.

**Comment by gh-andre** [comment]
Clearly, what I was suggesting doesn't align well with the philosophy for this package. I will close this now. Thank you for your insights.
