### ISSUE TITLE
How to handle JSON data always nested / wrapped in a "body" object

### ISSUE THREAD

**Issue by antgel** [marshmallow-code/webargs#895]
Hi everyone, it's been about four years since I was last around here. :)

I'm working on my Flask(-Classful) app again. On the client side, I moved from Frisbee to Axios. Now, all my JSON data is wrapped in a `body` object in the request.

i.e. `{ is_fun: true }` has become:
```json
{
  "body": {                                     
    "is_fun": true,           
  }                                    
}
```

I think it makes sense to abstract this behaviour out so I only define it in one place.

I think I need to implement a custom parser as per [these docs](https://webargs.readthedocs.io/en/5.5.3/advanced.html#custom-parsers) which would look something like:

```python
class NestedFieldParser(FlaskParser):
    def parse_json(self, req, name, field):
        json_data = req.get_json()
        nested_data = json_data.get("data", {})
        return super().parse_json(req, name, field, data=nested_data)
```

But then I'm a bit lost. Where would such a parser go? I don't see that `use_args` and `use_kwargs` can take a custom parser. 

To complicate (possibly) matters, I use a schema factory for `PATCH`ing:

```python
def use_args_with(schema_cls, schema_kwargs=None, **kwargs):
    schema_kwargs = schema_kwargs or {}

    def factory(request):
        # Filter based on 'fields' query parameter
        fields = request.args.get("fields", None)
        only = fields.split(",") if fields else None
        # Respect partial updates for PATCH requests
        partial = request.method == "PATCH"
        # Add current request to the schema's context
        return schema_cls(
            only=only, partial=partial, context={"request": request}, **schema_kwargs
        )

    return use_args(factory, **kwargs)
```

I'm on webargs 5.5.3 but can upgrade if necessary to make this easier. Also, am I on the right track? This seems like a lot of work for something that seems simple on the face of it. Also, feel free to critique my presumably rubbish coding "style"! :)

**Comment by sirosen** [comment]
Hi there! I think we can set aside most of your code complexity and zero in on only one issue:

> [successfully defining a custom parser]
>
> But then I'm a bit lost. Where would such a parser go? I don't see that `use_args` and `use_kwargs` can take a custom parser.

The key thing is that `use_args` and `use_kwargs` are provided by a parser, rather than being bare functions which can take a parser.

So what you probably want is
```python
# e.g., write this in parser.py
class NestedFieldParser(FlaskParser):
    ...

parser = NestedFieldParser()
use_args = parser.use_args
use_kwargs = parser.use_kwargs

# your custom helper
def use_args_with(...):
    ...
```
and then you can use it elsewhere as in
```python
from myapp.parser import use_args_with

@use_args_with(...)
def foo(...): ...
```

---

> I'm on webargs 5.5.3 but can upgrade if necessary to make this easier.

I don't know if it's necessary or even if it will make your current work easier, but I would strongly recommend upgrading at this stage. If I were you, I'd do it separately from any other changes, since it's quite likely that you'll need to make changes to handle the version upgrade(s).

We're currently on v8, and I've been a bit overwhelmed schedule-wise, so it's a little bit slow/stalled, but we're working our way towards webargs v9. Getting four major versions behind is pretty significant. v6.0.0 is probably the biggest single-step upgrade/update between 5.x and now, but you don't want to get locked into the past forever. For example, it's possible that we could fix a bug which impacts you, and you would not be able to pull in and apply that fix.

**Comment by antgel** [comment]
Thanks for the very helpful and prompt answer!

I was about to compose a reply based on the intricacies of my proposed custom parser implementation as my original ^^^ doesn't make sense; there's no `data` attribute in the `return`.

Then something strange happened. I pasted in the upstream `parse_json` method getting ready my custom parser, intending to modify it accordingly. I also reverted to webargs 5.5.3; I had forgotten that I had "temporarily" upgraded to 6.1.1 for reasons that escape me, probably trying to iron out some other bug. But before modifying the `parse_json` code from upstream, I noticed things were... working.

It seems that the 422 "caused by changing the client HTTP library", was in fact caused by upgrading webargs. :man_facepalming: When I reverted to webargs 5.x, the 422 went away (although I still had database errors because my schema wasn't finding the right fields because they're now in the "body" object. I really need to understand more about how webargs, marshmallow, and flask work together.)

I returned the client to the previous commit, and I can confirm that indeed the previous client didn't have the "body" wrapping object.

Here is my current working version. You'll notice I've just added `.get("body")` in one place. Is this the most efficient way to do this? I wanted to do a small manipulation then call the superclass `parse_json`. I tried to modify the output of `req.get_data` and modify `req` in place, but it seems to be immutable. I also tried a deep copy, but it wouldn't let me do that either (`cannot pickle '_io.BufferedReader' object`) and it's probably crap for performance.

```python
class NestedFieldParser(FlaskParser):
    def parse_json(self, req, name, field):
        json_data = self._cache.get("json")
        if json_data is None:
            if not is_json_request(req):
                return core.missing

            # We decode the json manually here instead of
            # using req.get_json() so that we can handle
            # JSONDecodeErrors consistently
            data = req.get_data(cache=True)
            try:
                self._cache["json"] = json_data = core.parse_json(data).get("body")  # <---
            except json.JSONDecodeError as e:
                if e.doc == "":
                    return core.missing
                else:
                    return self.handle_invalid_json_error(e, req)
        return core.get_value(json_data, name, field, allow_many_nested=True)
```

I think I'll need read the webargs v5-6 upgrade docs because apparently something in there doesn't like me. Before I close this, I would like to ask, does this sound like a plausible change in behaviour between webargs 5 and 6? And if so (and more generally), how should I go about digging for the cause of a 422?

**Comment by sirosen** [comment]
The v5-v6 upgrade makes a pretty dramatic change to the way that loading up data and parsing it with your schemas works. I would say that v6 is actually a lot easier to reason about, but that doesn't mean that it will be a smooth or trivial upgrade for an application which is already built with v5.

Under webargs v6+, there's a "loader" for each defined location, (`querystring`, `json`, `headers`, etc), which returns a dict or dict-like object. For `json` body data, it's pretty easy to understand: the request body as a dict. For query args and headers, which can take the same key multiple times, the datatype is a "multidict", so webargs has some special handling to interface with the data.
That means that as of v6, your `use_args/use_kwargs` decorators are setting a schema to use with the data from a given location -- "load JSON and pass that to schema X" is expressed with `use_args(SchemaX, location="json")`.

Under v5, every field was able to specify a separate location. So you could define a schema which took "`foo` from query params and `bar` from headers", mixing the locations into a single `use_args/use_kwargs` call. As a result, the location-loading framework used in v6+ isn't even applicable -- every time `webargs` is parsing data, it's potentially assembling it from multiple sources.

There are a lot of usages under v5 which are not only broken by an upgrade to v6 but actually considered unsupported and require adapting your usage in nontrivial ways.
For example, if you had the case I described above,
```python
@use_args({"foo": String(location="query"), "bar": String(location="header")})
```
that would work in v5, but needs to be broken apart in v6, e.g.
```python
@use_args({"foo": String()}, location="query")
@use_args({"bar": String()}, location="header")
```
and will could, in turn, change the shape of the data being passed to the decorated function.

In general, you should refer to the upgrading doc to handle this:
https://webargs.readthedocs.io/en/latest/upgrading.html

It has pretty solid guidance and explanations around v5->v6 (and later updates as well).

---

Right now, it's been so long since I was looking at the v5 code that I'm not sure what the best guidance would be.

If I were facing the problem you see, I'd probably not worry at all about performance for this purpose. Correctness is much more important than performance as a starting point. Once you have your application working and you have solid tests in place, you can optimize. Also, if you're using flask's request parsing and caching (e.g. `Request.json()` from flask), there's almost no perf penalty related to doing a repeated key lookup for `"body"`.

**Comment by antgel** [comment]
Thanks for that info, I have seen the link and am reading it every so often trying to understand more. I think the "problem" as far as my understanding goes at this stage is that I use [marshmallow schema integration](https://webargs.readthedocs.io/en/latest/advanced.html#marshmallow-integration) which is nice and automagic but hides some implementation details from me. (Also using marshmallow-sqlalchemy's `ModelSchema`, which I see is also old and discontinued, sigh...)

You're right about optimizing too early for performance. The performance penalty of the deep copy doesn't matter; the deep copy didn't work anyway. And the repeated key lookups aren't relevant; I don't do key lookups directly because I pass in the schema.

```python
@use_args_with(DogSchema)
@route("/<id>/stroke", methods=["PUT"])  # Provided by flask-classful
def stroke(self, args, id):
    bs = args.being_stroked  # Not request.data.get("being_stroked") nor request.data.get("body").get("being_stroked")
    ...
```

I understand what you are saying about the v6 location. I tend to use webargs for the JSON "location" only (feels more like a source than a location to me), I just wish there was a simpler way to pin it to the "body" object in my JSON. If what I've done works, then it's okay by me, but it just feels like this could be less complex.

The link above contains the tantalizing statement:
> The default location is JSON/body.

I'm just not sure what `/body` means, I think it should just say "JSON body" (no slash). It kind of looks like it will look for a `body: { }` object in the JSON. I wish. My head hurts from the overloading of "body"!

**Comment by sirosen** [comment]
> it just feels like this could be less complex.

FWIW, under version 8, I would suggest a `pre_load` method:
```python
class EnvelopedFlaskParser(FlaskParser):
    def pre_load(self, location_data, *, schema, req, location):
        if location == "json":
            return location_data.get("body", {})
        return location_data
```
I don't think it can get much simpler than that.

There are a couple of ways in which the v5 situation is more complex. I'm not shy about that -- I like to think that the work we've put in since then has made `webargs` even better! :smile: 

In particular, I find v5's use of an internal cache on the parser to be troubling. Personally, if I were building on top of it, I would cut that out of the implementation altogether and do any necessary caching on `flask.g` (which would let you do your own caching, attached to a request-context storage which is guaranteed to be isolated per request).

> > The default location is JSON/body.
>
> I'm just not sure what /body means, I think it should just say "JSON body" (no slash).

I read this as "JSON (i.e. the body of the request)". The slash was probably used to indicate that these are near-synonyms in this case, but I can try to rephrase for improved clarity.

"Body" is the term for the part of an HTTP request after the request line and headers. It definitely doesn't have to do with data enveloping or anything to do with a key named `"body"` -- there's nothing special (in the general case) about such a key.

**Comment by antgel** [comment]
Thank you. I reinstated my backing, it's the least I can do and I expect to be around for a while now, upgrading millions of packages and learning about how each contributes to the whole.

One more question (arguably OT for this issue) - where do real-time discussions happen these days? ISTR an IRC channel but I could be wrong. I found an email invite from 2019 to a Slack workspace but I went in and there were no messages in the last 90 days (I'm not a paying Slack user) so I'm assuming that workspace is no longer used?

Edit: And I will upgrade when I can! I just went through my main packages and it was somewhat sobering (latest versions in parentheses):
```
flask = "~=1.0.2" (3.0.0)
flask-classful = "~=0.14.2" (0.16.0)
flask-jwt-extended = "~=3.25.0" (4.5.3)
flask-marshmallow = "~=0.10.1" (0.15.0)
flask-sqlalchemy = "~=2.3.2" (3.1.1)
marshmallow = "~=3.0.0rc7" (3.20.1)
marshmallow-sqlalchemy = "~=0.17.0" (0.29.0)
sqlalchemy = "==1.3.1" (2.0.22)
sqlalchemy-mixins = "==1.2.1" (2.0.5)
webargs = "~=5.5.3" (8.3.0)
```

**Comment by sirosen** [comment]
> One more question (arguably OT for this issue) - where do real-time discussions happen these days? ISTR an IRC channel but I could be wrong. I found an email invite from 2019 to a Slack workspace but I went in and there were no messages in the last 90 days (I'm not a paying Slack user) so I'm assuming that workspace is no longer used?

I'm still in the Slack! I think it's just been super-quiet for so long that it has become the norm to not use it. I don't drop notes in the common channels, but I have made use of it to reach out to a couple of people directly once or twice.
I'm not aware of another channel for real-time conversations. I do most things over the slower async path of GitHub simply because it makes it way easier to juggle with my workday.

There's a whole discussion we could have about the benefits and costs of having an active real-time DM chat, but I don't want to get too OT from this ticket's starting point. :smile: 

---

Taking a quick glance at that dependency list, a couple of quick notes based on my own experiences using a subset of these packages.
- `flask` upgrades from 1.x to 2.0 and 2.x to 3.0 have been pretty low-friction on their own, but the other pallets dependencies move as well (e.g., `werkzeug`). So this requires some caution but hasn't been hard for me. Hopefully you have a similarly good experience!
- I recently (this year? last year? time is a blur) picked up maintenance of `flask-marshmallow`. I haven't gotten a full handle on the lib yet -- and I definitely don't know the diff from 0.10.1 to 0.14.0 -- but feel free to @-me if you file any issues related to your upgrade there.
- `marshmallow` 3.0.0rc7 -> 3.0.0 should probably be a pretty small change; I think this is one of your easier ones!
- `sqlalchemy` 1.3 to 1.4 should be low impact, and then there's a whole elaborate migration path for 1.4.x -> 2.0. If you get onto 1.4 , I think you can consider it "up to date for now", but know that the move to 2.0 is in your future.
- `webargs`, as discussed, will be a tricky one to handle for 5.x->6.0. But all of the major version bumps after that are pretty minor things -- mostly of the "technically backwards incompatible" flavor.

**Comment by lafrech** [comment]
[Indeed everything happens here. Since my company abandoned Slack for internal chat, I don't launch the client on startup any more. But I'd be notified if someone tried to reach us there. Thanks for the backing!]

**Comment by sirosen** [comment]
I'm closing this because the original topic seems to have been covered and the additional conversation seems to have trailed off (which, IMO, is fine).
